name: Compile
on: [push]
jobs:
  compile:
    name: Build thrift-compiler on ${{ matrix.os }}.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install macOS Dependencies
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          set -e
          brew install automake bison openssl
          echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH
          echo "CPPFLAGS=-I/usr/local/opt/openssl/include" >> $GITHUB_ENV
          echo "LDFLAGS=-L/usr/local/opt/openssl/lib" >> $GITHUB_ENV

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Build
        run: ./build.sh

      # - name: Save built artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: thrift-bins
      #     path: |
      #       dist
      #       !dist/**/*.md